#include <avr/pgmspace.h>
#include <stdint.h>

#include "definitions.h"

// Message: MSG_TYPE [MSG_BODY] CRC8

const uint8_t i2c_msg_sizes[I2C_MESSAGES_COUNT] = {
  [I2C_HELLO_CONTROLLER]=1,
  [I2C_SET_TIME]=3,
  [I2C_ENABLE_MOTORS]=1,
  [I2C_DISABLE_MOTORS]=1,
  [I2C_SPEED_UPDATE]=3,
  [I2C_TIMERSTOPWATCH_START]=3,
  [I2C_TIMERSTOPWATCH_STOP]=3,
  [I2C_TIMERSTOPWATCH_IS_TIMER]=1,
  [I2C_TIMERSTOPWATCH_IS_STOPWATCH]=1,
  [I2C_TIMERSTOPWATCH_RESET]=1,
  [I2C_COEF_UPDATE]=3,
};