#ifndef COMMON_H
#define COMMON_H

#ifndef CONTROLLER1_ADDRESS
#define CONTROLLER1_ADDRESS 0x10
#endif
#ifndef CONTROLLER2_ADDRESS
#define CONTROLLER2_ADDRESS 0x11
#endif

#ifndef I2C_FREQUENCY
#define I2C_FREQUENCY 100000 // Normal mode by default
#endif

#define I2C_HELLO 0
#define I2C_SET_TIME 1
#define I2C_ENABLE_MOTORS 2
#define I2C_DISABLE_MOTORS 3
#define I2C_SPEED_UPDATE 4
#define I2C_TIMERSTOPWATCH_START 5
#define I2C_TIMERSTOPWATCH_STOP 6
#define I2C_TIMERSTOPWATCH_IS_TIMER 7
#define I2C_TIMERSTOPWATCH_IS_STOPWATCH 8
#define I2C_TIMERSTOPWATCH_RESET 9
#define I2C_COEF_UPDATE 10
#define I2C_MESSAGES_COUNT 11

extern const PROGMEM uint8_t i2c_msg_sizes[I2C_MESSAGES_COUNT];

#endif // COMMON_H
